version: '3'
services:

  postgres:
    image: postgres
    container_name: postgres
    expose:
      - 5432
    restart: always
    env_file:
      - project/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - postgres


volumes:
  postgres-db: